### ISSUE TITLE
Cannot connect to mypads admin panel

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/etherpad_mypads_ynh#134]
Fresh install of etherpad_mypads.

I can connect to the etherpad admin panel (with credentials set at install), but not to the mypads administration: It says incorrect password (with same credentials)
PS: this is not a typo ;)

YunoHost version: 
```
yunohost: 
  repo: stable
  version: 4.1.7.4
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3

```
