### ISSUE TITLE
Upgrade fails 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/etherpad_mypads_ynh#43]
I tired to upgrade but the upgrade fails and now I have 502 bad gateway. How can I fix this, reinstall is not an option as I have lot of pads.

The normal upgrade script was so long that the error part vanished from the command-line.
Here is the etherpad.log : 
```
[2018-05-27 XX:XX:XX:XXX] [WARN] console - DirtyDB is used. This is fine for testing but not recommended for production.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/var/www/etherpad_mypads/dirty.db'
    at Error (native)
RESTART!
```
Yunohost version:
```
yunohost: 
  repo: testing
  version: 2.7.13.2
yunohost-admin: 
  repo: testing
  version: 2.7.13
moulinette: 
  repo: stable
  version: 2.7.12
ssowat: 
  repo: stable
  version: 2.7.12

```
Nginx log for the domain : 

`2018/05/27 XX:XX:XX [error] 11376#0: *16943 connect() failed (111: Connection refused) while connecting to upstream, client: XX:XX:XX:XX, server: pad.xxxxxxxxx.xxx request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:9001/favicon.ico", host: "pad.xxxxxxxxx.xxx", referrer: "https://pad.xxxxxxxxx.xxx/"`
